### ISSUE TITLE
Broken formatting in \d

### ISSUE THREAD

**Issue by j-bennet** [dbcli/litecli#37] opened 2019-01-04 23:13 UTC
Here's one odd looking tabulate.

Litecli version: 1.0.0

```
~/repos/engineering/rebuilds.sqlite> \d
+------------------------------------------------------------------------------+
| sql                                                                          |
+------------------------------------------------------------------------------+
| CREATE TABLE abc(a text)                                                     |
| CREATE TABLE rebuild_jobs_local (                                            |
|       id INTEGER NOT NULL,                                                        |
|       source VARCHAR(9),                                                          |
|       started DATETIME,                                                           |
|       submitted DATETIME,                                                         |
|       finished DATETIME,                                                          |
|       start_date DATETIME NOT NULL,                                               |
|       end_date DATETIME NOT NULL,                                                 |
|       apikeys TEXT NOT NULL,                                                      |
|       args TEXT,                                                                  |
|       rq_job_id TEXT,                                                             |
|       updated DATETIME DEFAULT CURRENT_TIMESTAMP,                                 |
|       PRIMARY KEY (id),                                                           |
|       CONSTRAINT rebuildsource CHECK (source IN ('daily', 'autobuild', 'manual')) |
| )                                                                            |
```

**Comment by j-bennet** [comment] 2019-01-08 16:17
Why would that be?

**Comment by zzl0** [comment] 2019-01-12 18:05
It was just a wild guess. I have found an easy way to reproduce it.

## How to reproduce?

Since `litecli` doesn't allow me to type `tab` in the REPL, I used `sqlite3` CLI to create a table as below

``` bash
$ sqlite3 ex1
sqlite> create table aaa (
   ...> 	bbb varchar not null
   ...> );
```

Verified the output in `litecli`:

``` bash
$ litecli ex2
Version: 1.0.0
Mail: https://groups.google.com/forum/#!forum/litecli-users
Github: https://github.com/dbcli/litecli
ex2> \d
+-----------------------+
| sql                   |
+-----------------------+
| CREATE TABLE aaa (    |
| 	bbb varchar not null |
| )                     |
+-----------------------+
Time: 0.013s
```

## Why would that be?

It's a problem of `TabularOutputFormatter` in `cli_helpers`, because the table formatter treat `tab` as normal character while the terminal treat it in a different way (e.g. 4 or 8 space wide), here is how to reproduce it with `TabularOutputFormatter`:

``` text
>>> from cli_helpers.tabular_output import TabularOutputFormatter
>>> formatter = TabularOutputFormatter('ascii')
>>> def format_table(table, headers):
...     for i in formatter.format_output(table, headers):
...         print(i)
...
>>> table = [["CREATE TABLE aaa ("], [" bbb varchar not null"]]
>>> headers = ["tables"]
>>> format_table(table, headers)
+-----------------------+
| tables                |
+-----------------------+
| CREATE TABLE aaa (    |
| 	bbb varchar not null |
+-----------------------+
```

## Possible way to solove it

``` text
>>> table2 = [[i.replace('\t', ' '*4) for i in row] for row in table]
>>> format_table(table2, headers)
+--------------------------+
| tables                   |
+--------------------------+
| CREATE TABLE aaa (       |
|     bbb varchar not null |
+--------------------------+
```

The is just a rough idea, we need to be careful to replace tab, because a default value might also contains `tab`. 

If you agree with this approach, I can continute to think about how to fix it and submit a PR to `cli_helpers`.

**Comment by meeuw** [comment] 2019-01-12 19:57
This should be fixed in cli_helpers (as a preprocessor) or even tabulate / terminal tables. Mycli/pgcli have the same issue with tabs.

We might also consider replacing tabs with `\t` or `↹`

**Closed** 2019-03-26 23:34 UTC
