### ISSUE TITLE
Incomplete, multi-line CREATE TABLE with .schema  

### ISSUE THREAD

**Issue by elig0n** [dbcli/litecli#58] opened 2019-05-21 06:09 UTC
Under regular `sqlite3` `.schema` command displays my database schema properly.
But under `litecli` a multi-line CREATE TABLE is cut weirdly only after a few column description lines.
No special character I detected at the cut point (I've checked with an hex editor).
Each indented line is using only spaces.

Example:

    exampledb.sqlite3> .schema
    sql
    CREATE TABLE example_table ( col0_name TEXT,
                                                col1_name TEXT,
                                                col2_name TEXT,
                                                c
    <null>
    CREATE TABLE .... [one-liners, all displayed alright]

Tried with several \T options and with different `less` pager options and `cat`.

Queries are fine and everything else works alright though.

**Comment by amjith** [comment] 2019-05-22 01:19
I'm not able to reproduce this locally. Do you have the exact create statement that you used? 

Perhaps you can paste the output of `.schema` from the sqlite3 cli.

**Comment by elig0n** [comment] 2019-05-23 10:25
@amjith Please try with this: https://pastebin.com/raw/Uyrs2hfA

**Comment by amjith** [comment] 2019-05-26 05:29
I'm able to reproduce it. Thank you for your example. Trying to figure out the fix now.

**Comment by amjith** [comment] 2019-05-26 06:53
@tsroten I found an interesting issue with cli_helpers that I'm not sure how to solve. 

One of the preprocessors applied by tabulate_adapter is [truncate_string](https://github.com/dbcli/cli_helpers/blob/master/cli_helpers/tabular_output/preprocessors.py#L11). 

But in this specific issue where the CREATE TABLE statement is mutli-line there result can often be longer than the 500 characters but it is broken up into multiple lines using `\n` characters. 

Ideally, I would want to override the default preprocessors for the tabulate adapter when I know that there is a reason to do so. But with the way the code is structured, I can specify additional preprocessors but I can't override the existing ones. 

So I'm wondering what would be the best way to proceed?

**Comment by tsroten** [comment] 2019-05-26 12:12
@amjith I can definitely see a use case for disabling preprocessors in general. There is a way to disable the `truncate_string` preprocessor, which is to pass `max_field_width=None` as a keyword argument when you call `format_output()`. Would that work?

**Comment by amjith** [comment] 2019-05-26 14:14
I'll give that a shot. Thank you for the tip.

**Comment by amjith** [comment] 2019-07-14 21:20
This is now fixed in `cli_helpers` and released. Please upgrade cli_helpers by running: 

```
pip install -U cli_helpers
```

**Closed by amjith** 2019-07-14 21:20 UTC
